# Generated by Django 4.0.3 on 2022-04-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_alter_project_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('certification_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
