# Generated by Django 4.0.3 on 2022-04-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_certifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications',
            name='certification_image',
        ),
        migrations.AddField(
            model_name='certifications',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
